// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: time_window.
// - Entity ID: 102019a1d9558e97eb7aeb8d16618570c05.
// - Entity Version: 102019a1dd7e1a171efb6467029843c5d0e.
// - Task ID: 68fd664019a61d1ab43a9dbc.
// - Task Root ID: 68fd5421128d32154869dba1.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";







/**
 * Enumeration for TimeWindowStatus
 */
export enum TimeWindowStatus {
  Unspecified = 0,
  Open = 1,
  PartiallyBooked = 2,
  FullyBooked = 3,
  Closed = 4,
}



/**
 * Interface for TimeWindowModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface TimeWindowModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  clinician_id: string;
  patient_id: string;
  procedure_ids: string[];
  start_date: string;
  end_date: string;
  available_time_blocks?: string | null;
  status: TimeWindowStatus;
}

/**
 * ORM class for TimeWindow entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class TimeWindowORM {
  private static instance: TimeWindowORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019a1d9558e97eb7aeb8d16618570c05';
    this.entityName = 'time_window';
    this.entityVersion = '102019a1dd7e1a171efb6467029843c5d0e';
    this.taskId = '68fd664019a61d1ab43a9dbc';
    this.taskRootId = '68fd5421128d32154869dba1';
  }

  /**
   * Get singleton instance of TimeWindowORM
   */
  public static getInstance(): TimeWindowORM {
    if (!TimeWindowORM.instance) {
      TimeWindowORM.instance = new TimeWindowORM();
    }
    
    return TimeWindowORM.instance;
  }

  /**
   * Get all TimeWindow records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllTimeWindow(): Promise<TimeWindowModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new TimeWindow record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertTimeWindow(data: TimeWindowModel[]): Promise<TimeWindowModel[]> {
    const structured = data.map((item) => CreateData(TimeWindowModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all TimeWindow records
   */
  async purgeAllTimeWindow(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List TimeWindow records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listTimeWindow(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[TimeWindowModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get time_window by Id index
   * This function gets data by index.
   */
  async getTimeWindowById(
    id: string,
  ): Promise<TimeWindowModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) time_window by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setTimeWindowById(
    id: string,
    data: TimeWindowModel
  ): Promise<TimeWindowModel[]> {
    const index = createIndexId(
      id
    );

    const values = TimeWindowModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete time_window by Id index
   */
  async deleteTimeWindowById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get time_window by DataCreator index
   * This function gets data by index.
   */
  async getTimeWindowByDataCreator(
    data_creator: string,
  ): Promise<TimeWindowModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) time_window by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setTimeWindowByDataCreator(
    data_creator: string,
    data: TimeWindowModel
  ): Promise<TimeWindowModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = TimeWindowModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete time_window by DataCreator index
   */
  async deleteTimeWindowByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get time_window by DataUpdater index
   * This function gets data by index.
   */
  async getTimeWindowByDataUpdater(
    data_updater: string,
  ): Promise<TimeWindowModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) time_window by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setTimeWindowByDataUpdater(
    data_updater: string,
    data: TimeWindowModel
  ): Promise<TimeWindowModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = TimeWindowModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete time_window by DataUpdater index
   */
  async deleteTimeWindowByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get time_window by ClinicianId index
   * This function gets data by index.
   */
  async getTimeWindowByClinicianId(
    clinician_id: string,
  ): Promise<TimeWindowModel[]> {
    const index = createIndexClinicianId(
      clinician_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) time_window by ClinicianId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setTimeWindowByClinicianId(
    clinician_id: string,
    data: TimeWindowModel
  ): Promise<TimeWindowModel[]> {
    const index = createIndexClinicianId(
      clinician_id
    );

    const values = TimeWindowModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete time_window by ClinicianId index
   */
  async deleteTimeWindowByClinicianId(
    clinician_id: string
  ): Promise<void> {
    const index = createIndexClinicianId(
      clinician_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get time_window by PatientId index
   * This function gets data by index.
   */
  async getTimeWindowByPatientId(
    patient_id: string,
  ): Promise<TimeWindowModel[]> {
    const index = createIndexPatientId(
      patient_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) time_window by PatientId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setTimeWindowByPatientId(
    patient_id: string,
    data: TimeWindowModel
  ): Promise<TimeWindowModel[]> {
    const index = createIndexPatientId(
      patient_id
    );

    const values = TimeWindowModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete time_window by PatientId index
   */
  async deleteTimeWindowByPatientId(
    patient_id: string
  ): Promise<void> {
    const index = createIndexPatientId(
      patient_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get time_window by Status index
   * This function gets data by index.
   */
  async getTimeWindowByStatus(
    status: TimeWindowStatus,
  ): Promise<TimeWindowModel[]> {
    const index = createIndexStatus(
      status
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) time_window by Status index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setTimeWindowByStatus(
    status: TimeWindowStatus,
    data: TimeWindowModel
  ): Promise<TimeWindowModel[]> {
    const index = createIndexStatus(
      status
    );

    const values = TimeWindowModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete time_window by Status index
   */
  async deleteTimeWindowByStatus(
    status: TimeWindowStatus
  ): Promise<void> {
    const index = createIndexStatus(
      status
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get time_window by ClinicianIdStatus index
   * This function gets data by index.
   */
  async getTimeWindowByClinicianIdStatus(
    clinician_id: string,
    status: TimeWindowStatus,
  ): Promise<TimeWindowModel[]> {
    const index = createIndexClinicianIdStatus(
      clinician_id,
      status
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) time_window by ClinicianIdStatus index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setTimeWindowByClinicianIdStatus(
    clinician_id: string,
    status: TimeWindowStatus,
    data: TimeWindowModel
  ): Promise<TimeWindowModel[]> {
    const index = createIndexClinicianIdStatus(
      clinician_id,
      status
    );

    const values = TimeWindowModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete time_window by ClinicianIdStatus index
   */
  async deleteTimeWindowByClinicianIdStatus(
    clinician_id: string,
    status: TimeWindowStatus
  ): Promise<void> {
    const index = createIndexClinicianIdStatus(
      clinician_id,
      status
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get time_window by PatientIdStatus index
   * This function gets data by index.
   */
  async getTimeWindowByPatientIdStatus(
    patient_id: string,
    status: TimeWindowStatus,
  ): Promise<TimeWindowModel[]> {
    const index = createIndexPatientIdStatus(
      patient_id,
      status
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) time_window by PatientIdStatus index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setTimeWindowByPatientIdStatus(
    patient_id: string,
    status: TimeWindowStatus,
    data: TimeWindowModel
  ): Promise<TimeWindowModel[]> {
    const index = createIndexPatientIdStatus(
      patient_id,
      status
    );

    const values = TimeWindowModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete time_window by PatientIdStatus index
   */
  async deleteTimeWindowByPatientIdStatus(
    patient_id: string,
    status: TimeWindowStatus
  ): Promise<void> {
    const index = createIndexPatientIdStatus(
      patient_id,
      status
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get time_window by ClinicianIdStartDate index
   * This function gets data by index.
   */
  async getTimeWindowByClinicianIdStartDate(
    clinician_id: string,
    start_date: string,
  ): Promise<TimeWindowModel[]> {
    const index = createIndexClinicianIdStartDate(
      clinician_id,
      start_date
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) time_window by ClinicianIdStartDate index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setTimeWindowByClinicianIdStartDate(
    clinician_id: string,
    start_date: string,
    data: TimeWindowModel
  ): Promise<TimeWindowModel[]> {
    const index = createIndexClinicianIdStartDate(
      clinician_id,
      start_date
    );

    const values = TimeWindowModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete time_window by ClinicianIdStartDate index
   */
  async deleteTimeWindowByClinicianIdStartDate(
    clinician_id: string,
    start_date: string
  ): Promise<void> {
    const index = createIndexClinicianIdStartDate(
      clinician_id,
      start_date
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to TimeWindowModel data array
   */
  private resultToData(values: Data[]): TimeWindowModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return TimeWindowModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as TimeWindowModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized TimeWindowModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is TimeWindowModel => item !== null);
  }
}

/**
 * Convert TimeWindowModel data to Value array
 */
function TimeWindowModelToValues(data: TimeWindowModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'clinician_id', type: DataType.string, defaultValue: '' },
    { key: 'patient_id', type: DataType.string, defaultValue: '' },
    { key: 'procedure_ids', type: DataType.array, defaultValue: [] },
    { key: 'start_date', type: DataType.string, defaultValue: '' },
    { key: 'end_date', type: DataType.string, defaultValue: '' },
    { key: 'available_time_blocks', type: DataType.string, defaultValue: null },
    { key: 'status', type: DataType.enumeration, defaultValue: 0 },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof TimeWindowModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to TimeWindowModel data
 */
function TimeWindowModelFromValues(values: Value[]): TimeWindowModel {
  const data: Partial<TimeWindowModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'clinician_id':
        data.clinician_id = ParseValue(value, DataType.string) as string;
        break;
      case 'patient_id':
        data.patient_id = ParseValue(value, DataType.string) as string;
        break;
      case 'procedure_ids':
        data.procedure_ids = ParseValue(value, DataType.array) as string[];
        break;
      case 'start_date':
        data.start_date = ParseValue(value, DataType.string) as string;
        break;
      case 'end_date':
        data.end_date = ParseValue(value, DataType.string) as string;
        break;
      case 'available_time_blocks':
        data.available_time_blocks = ParseValue(value, DataType.string) as string | null;
        break;
      case 'status':
        data.status = ParseValue(value, DataType.enumeration) as TimeWindowStatus;
        break;
    }
  }
  
  return data as TimeWindowModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}
/**
 * Create index for ClinicianId fields
 */
function createIndexClinicianId(
  clinician_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, clinician_id, 'clinician_id'),
  ];

  return {
    fields: ['clinician_id'],
    values
  };
}
/**
 * Create index for PatientId fields
 */
function createIndexPatientId(
  patient_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, patient_id, 'patient_id'),
  ];

  return {
    fields: ['patient_id'],
    values
  };
}
/**
 * Create index for Status fields
 */
function createIndexStatus(
  status: TimeWindowStatus
): Index {
  const values: Value[] = [
    CreateValue(DataType.enumeration, status, 'status'),
  ];

  return {
    fields: ['status'],
    values
  };
}
/**
 * Create index for ClinicianIdStatus fields
 */
function createIndexClinicianIdStatus(
  clinician_id: string,
  status: TimeWindowStatus
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, clinician_id, 'clinician_id'),
    CreateValue(DataType.enumeration, status, 'status'),
  ];

  return {
    fields: ['clinician_id', 'status'],
    values
  };
}
/**
 * Create index for PatientIdStatus fields
 */
function createIndexPatientIdStatus(
  patient_id: string,
  status: TimeWindowStatus
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, patient_id, 'patient_id'),
    CreateValue(DataType.enumeration, status, 'status'),
  ];

  return {
    fields: ['patient_id', 'status'],
    values
  };
}
/**
 * Create index for ClinicianIdStartDate fields
 */
function createIndexClinicianIdStartDate(
  clinician_id: string,
  start_date: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, clinician_id, 'clinician_id'),
    CreateValue(DataType.string, start_date, 'start_date'),
  ];

  return {
    fields: ['clinician_id', 'start_date'],
    values
  };
}

export default TimeWindowORM;