/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SigninImport } from './routes/signin'
import { Route as JwtDebugImport } from './routes/jwt-debug'
import { Route as IndexImport } from './routes/index'
import { Route as AuthGoogleCallbackImport } from './routes/auth.google.callback'

// Create/Update Routes

const SigninRoute = SigninImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRoute,
} as any)

const JwtDebugRoute = JwtDebugImport.update({
  id: '/jwt-debug',
  path: '/jwt-debug',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthGoogleCallbackRoute = AuthGoogleCallbackImport.update({
  id: '/auth/google/callback',
  path: '/auth/google/callback',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/jwt-debug': {
      id: '/jwt-debug'
      path: '/jwt-debug'
      fullPath: '/jwt-debug'
      preLoaderRoute: typeof JwtDebugImport
      parentRoute: typeof rootRoute
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninImport
      parentRoute: typeof rootRoute
    }
    '/auth/google/callback': {
      id: '/auth/google/callback'
      path: '/auth/google/callback'
      fullPath: '/auth/google/callback'
      preLoaderRoute: typeof AuthGoogleCallbackImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/jwt-debug': typeof JwtDebugRoute
  '/signin': typeof SigninRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/jwt-debug': typeof JwtDebugRoute
  '/signin': typeof SigninRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/jwt-debug': typeof JwtDebugRoute
  '/signin': typeof SigninRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/jwt-debug' | '/signin' | '/auth/google/callback'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/jwt-debug' | '/signin' | '/auth/google/callback'
  id: '__root__' | '/' | '/jwt-debug' | '/signin' | '/auth/google/callback'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JwtDebugRoute: typeof JwtDebugRoute
  SigninRoute: typeof SigninRoute
  AuthGoogleCallbackRoute: typeof AuthGoogleCallbackRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JwtDebugRoute: JwtDebugRoute,
  SigninRoute: SigninRoute,
  AuthGoogleCallbackRoute: AuthGoogleCallbackRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/jwt-debug",
        "/signin",
        "/auth/google/callback"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/jwt-debug": {
      "filePath": "jwt-debug.tsx"
    },
    "/signin": {
      "filePath": "signin.tsx"
    },
    "/auth/google/callback": {
      "filePath": "auth.google.callback.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
